In [1]:
import cv2
import numpy as np
import imutils

In [3]:
src = cv2.imread('./data/rect.jpg')
gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 50, 100)
lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180.0, threshold=100)

print('lines.shape=', lines.shape)

for line in lines:
    x1, y1, x2, y2   = line[0]
    cv2.line(src,(x1,y1),(x2,y2),(0,0,255),2)
    
cv2.imshow('edges',  edges)
cv2.imshow('src',  src)
cv2.waitKey()
cv2.destroyAllWindows()

lines.shape= (4, 1, 4)


In [7]:
src1 = cv2.imread('./data/circles.jpg')
gray1 = cv2.cvtColor(src1,cv2.COLOR_BGR2GRAY)
circles1 = cv2.HoughCircles(gray1, method=cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=16)           
print(circles1)
circles1 = np.uint16(np.around(circles1))
print(circles1)
print('circles1.shape=', circles1.shape)
for circle in circles1[0,:]:    
    cx, cy, r  = circle
    cv2.circle(src1, (cx, cy), r, (0,0,255), 2)

#2
src2 = cv2.imread('./data/circles2.jpg')
gray2 = cv2.cvtColor(src2,cv2.COLOR_BGR2GRAY)
circles2 = cv2.HoughCircles(gray2, method=cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15, minRadius=30, maxRadius=100)

circles2 = np.uint16(np.around(circles2))
print('circles2.shape=', circles2.shape)
for circle in circles2[0,:]:    
    cx, cy, r  = circle
    cv2.circle(src2, (cx, cy), r, (0,0,255), 2) 
    
cv2.imshow('src1',  src1)
cv2.imshow('src2',  src2)
cv2.waitKey()
cv2.destroyAllWindows()

[[[228.5 220.5  76.1]
  [369.5 147.5  62.2]
  [344.5 391.5  53.2]]]
[[[228 220  76]
  [370 148  62]
  [344 392  53]]]
circles1.shape= (1, 3, 3)
circles2.shape= (1, 6, 3)
